{{- if and (or (.Values.s3.customServerConf) (.Values.s3.customLocationConf)) (.Values.enabled) -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-conf
data:
  {{ if .Values.s3.customServerConf }}
  s3_server.conf.template: {{ quote .Values.s3.customServerConf }}
  {{ end }}
  {{ if .Values.s3.customLocationConf }}
  s3_location.conf.template: {{ quote .Values.s3.customLocationConf }}
  {{ end }}
{{- end }}