{{- $tracingUrl := include "nginx-s3-gateway.tracingUrl" . -}}
{{- $metricsUrl := include "nginx-s3-gateway.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  AWS_ACCESS_KEY_ID: {{ quote .Values.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ quote .Values.s3.secretAccessKey }}
  S3_BUCKET_NAME: {{ quote .Values.s3.bucketName }}
  S3_SERVER: {{ quote .Values.s3.server }}
  S3_SERVER_PORT: {{ quote .Values.s3.serverPort }}
  S3_SERVER_PROTO: {{ quote .Values.s3.serverProto }}
  S3_REGION: {{ quote .Values.s3.region }}
  S3_STYLE: {{ quote .Values.s3.style }}
  DEBUG: {{ quote .Values.s3.debug }}
  AWS_SIGS_VERSION: {{ quote .Values.aws.sigsVersion }}
  ALLOW_DIRECTORY_LIST: {{ quote .Values.global.allowDirectoryList }}
  HEADER_TOKEN: {{ quote .Values.authentication.opa.customHeaderName }}
  NGINX_WORKER_PROCESSES: {{ quote .Values.s3.nginxWorkerProcesses }}
  PROXY_CACHE_MAX_SIZE: {{ quote .Values.s3.cacheMaxSize }}
  PROXY_CACHE_INACTIVE: {{ quote .Values.s3.cacheInactive }}
  PROXY_CACHE_VALID_OK: {{ quote .Values.s3.cacheValidOk }}
  PROXY_CACHE_VALID_NOTFOUND: {{ quote .Values.s3.cacheValidNotfound }}
  PROXY_CACHE_VALID_FORBIDDEN: {{ quote .Values.s3.cacheValidForbidden }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
