{{- if .Values.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-custom
data:
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
  {{ if .Values.s3.customServerConf }}
  s3_server.conf.template: {{ quote .Values.s3.customServerConf }}
  {{ end }}
  {{ if .Values.s3.customLocationConf }}
  s3_location.conf.template: {{ quote .Values.s3.customLocationConf }}
  {{ end }}
{{- end }}