kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-custom
data:
  {{-  $serving := (include "common.serving.merged" . ) | fromYaml }}
  {{ if $serving.authorization.enabled }}
  auth.js: {{ tpl (.Files.Get "config/auth.js") . | quote }}
  {{ end }}
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
  nginx.conf.template: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
  default.conf.template: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  redis-get-key.lua: {{ tpl (.Files.Get "config/redis-get-key.lua") . | quote }}
  redis-set-key.lua: {{ tpl (.Files.Get "config/redis-set-key.lua") . | quote }}
  {{ if .Values.customServerConf }}
  s3_server.conf.template: {{ quote .Values.customServerConf }}
  {{ end }}
  {{ if .Values.customLocationConf }}
  s3_location.conf.template: {{ quote .Values.customLocationConf }}
  {{ end }}