{{- if .Values.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-custom
data:
  21-envsubst-on-nginx-conf.sh: {{ .Files.Get "config/21-envsubst-on-nginx-conf.sh" | quote }}
  auth.js: {{ tpl (.Files.Get "config/auth.js") . | quote }}
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
  default.conf.template: {{ tpl (.Files.Get "config/default.conf.template") . | quote }}
  nginx.conf.template: {{ tpl (.Files.Get "config/nginx.conf.template") . | quote }}
  {{ if .Values.s3.customServerConf }}
  s3_server.conf.template: {{ quote .Values.s3.customServerConf }}
  {{ end }}
  {{ if .Values.s3.customLocationConf }}
  s3_location.conf.template: {{ quote .Values.s3.customLocationConf }}
  {{ end }}
{{- end }}