{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx-s3-gateway.name" . -}}
{{- $fullName := include "nginx-s3-gateway.fullname" . -}}
{{- $cloudProviderFlavor := include "nginx-s3-gateway.cloudProviderFlavor" . -}}
{{- $tag := include "nginx-s3-gateway.tag" . -}}
{{- $cloudProviderImagePullSecretName := include "nginx-s3-gateway.cloudProviderImagePullSecretName" . -}}
{{- $cloudProviderDockerRegistryUrl := include "nginx-s3-gateway.cloudProviderDockerRegistryUrl" . -}}
{{- $podAnnotations := (include "merged.podAnnotations" . ) | fromYaml }}
{{- $extraVolumes := (include "merged.extraVolumes" . ) | fromYaml }}
{{- $extraVolumeMounts := (include "merged.extraVolumeMounts" . ) | fromYaml }}
{{- $sidecars := (include "merged.sidecars" . ) | fromYaml }}
{{- $opala := (include "merged.opala" . ) | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "nginx-s3-gateway.environment" . }}
    release: {{ $releaseName }}
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $fullName }}
      {{- include "nginx-s3-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $fullName }}
        {{- include "nginx-s3-gateway.selectorLabels" . | nindent 8 }}
      annotations:
        {{ include "merged.podAnnotations" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      containers:
        - name: {{ $fullName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $tag }}
          {{- end }}
          volumeMounts:
            {{ if $opala.enabled }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/auth.js
              subPath: auth.js
            {{ end }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/log_format.conf
              subPath: log_format.conf
            - name: nginx-custom-conf
              mountPath: /etc/nginx/nginx.conf.template
              subPath: nginx.conf.template
            - name: nginx-custom-conf
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: nginx-custom-conf
              mountPath: /etc/nginx/lua/redis-get-key.lua
              subPath: redis-get-key.lua
            - name: nginx-custom-conf
              mountPath: /etc/nginx/lua/redis-set-key.lua
              subPath: redis-set-key.lua
            {{- if .Values.customServerConf }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/templates/gateway/s3_server.conf.template
              subPath: s3_server.conf.template
            {{- end }}
            {{- if .Values.customLocationConf }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/templates/gateway/s3_location.conf.template
              subPath: s3_location.conf.template
            {{- end }}
            {{- if $extraVolumeMounts -}}
              {{ toYaml $extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
        {{- if $sidecars }}
        {{ tpl ($sidecars) . | nindent 8 }}
        {{- end }}
      volumes:
        - name: nginx-custom-conf
          configMap:
            name: {{ $fullName }}-custom
        {{- if $extraVolumes -}}
        {{ tpl (toYaml $extraVolumes) . | nindent 8 }}
        {{- end }}
