{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx-s3-gateway.name" . -}}
{{- $cloudProviderFlavor := include "nginx-s3-gateway.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "nginx-s3-gateway.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "nginx-s3-gateway.cloudProviderImagePullSecretName" . -}}
{{- $tag := include "nginx-s3-gateway.tag" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-deployment
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "nginx-s3-gateway.environment" . }}
    release: {{ $releaseName }}
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "nginx-s3-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "nginx-s3-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      volumes:
        {{- if .Values.authentication.opa.enabled }}
        - name: opa-policy
          secret:
            secretName: {{ .Release.Name }}-opa
        - name: proxy-config
          configMap:
            name: {{ .Release.Name }}-envoy
        - name: jwt-public-keys
          secret:
            secretName: {{ .Values.authentication.jwtPublicKeySecretName }}
        {{- end }}
        - name: nginx-custom-conf
          configMap:
            name: {{ .Release.Name }}-location
        {{- if .Values.logsFilebeat.enabled }}
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat-config
        {{- end }}
      containers:
        - name: {{ $releaseName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $tag }}
          {{- end }}
          # For debugging uncomment the following lines
          # command:
          #   - sleep
          #   - infinity
          volumeMounts:
            {{- if .Values.s3.customServerConf }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/templates/gateway/s3_server.conf.template
              subPath: s3_server.conf.template
            {{- end }}
            {{- if .Values.s3.customLocationConf }}
            - name: nginx-custom-conf
              mountPath: /etc/nginx/templates/gateway/s3_location.conf.template
              subPath: s3_location.conf.template
            {{- end }}
            {{- if .Values.logsFilebeat.enabled }}
            - name: logs
              mountPath: {{ .Values.logsFilebeat.mountPath }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.env.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.authentication.opa.enabled }}
        - name: envoy
          image: "{{ .Values.envoy.image }}:{{ .Values.envoy.imageTag }}"
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: proxy-config
          - name: jwt-public-keys
            readOnly: true
            mountPath: /keys/mapColonies.jwks
            subPath: mapColonies.jwks
          args:
          - "envoy"
          - "--config-path"
          - "/config/envoy.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.envoy.port }}
              protocol: {{ .Values.env.protocol }}
            - name: admin
              containerPort: {{ .Values.envoy.port }}
              protocol: {{ .Values.env.protocol }}
          # livenessProbe:
          #   httpGet:
          #     path: /health?plugins
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health?plugins
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 30
          {{- if .Values.envoy.resources.enabled }}
          resources:
            {{- toYaml .Values.envoy.resources.value | nindent 12 }}
          {{- end }}
        - name: opa
          image: "{{ .Values.opa.image }}:{{ .Values.opa.imageTag }}"
          volumeMounts:
          - readOnly: true
            mountPath: /policy
            name: opa-policy
          args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
          - "--set=plugins.envoy_ext_authz_grpc.add=:{{ .Values.opa.imageTag }}"
          - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"
          {{- if .Values.opa.enableLogging }}
          - "--set=decision_logs.console=true"
          {{- end }}
          - "/policy/policy.rego"
          {{- if .Values.opa.resources.enabled }}
          resources:
            {{- toYaml .Values.opa.resources.value | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 30
        {{- end }}
        {{- if .Values.logsFilebeat.enabled }}
        - name: filebeat
          image: {{ .Values.logsFilebeat.filebeatImage }}
          args: [ "-c", "/etc/filebeat.yml", "-e" ]
          volumeMounts:
            - name: logs
              mountPath: {{ .Values.logsFilebeat.mountPath }}
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
        {{- end }}
{{- end }}
