{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if eq .Values.ingress.type "nginx-kubernetes" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- if eq .Values.ingress.type "nginx-org" }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}{{ .Release.Name }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-service
            port:
              number: {{ .Values.ports.nginx.targetPort }}
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host | quote }}
    {{ end }}
{{ end }}
