{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx-s3-gateway.name" . -}}
{{- $cloudProviderFlavor := include "nginx-s3-gateway.cloudProviderFlavor" . -}}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $releaseName }}-route
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  to:
    kind: Service
    name: {{ $releaseName }}
  {{- if .Values.route.https }}
  tls:
    termination: edge
  {{- end }}
{{ end }}