{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx-s3-gateway.name" . -}}
{{- $cloudProviderFlavor := include "nginx-s3-gateway.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "nginx-s3-gateway.environment" . }}
    release: {{ $releaseName }}
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - name: internal
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
    {{- if .Values.authentication.opa.enabled }}
    - name: external
      port: {{ .Values.env.targetPort }}
      targetPort: {{ .Values.envoy.port }}
      protocol: {{ .Values.env.protocol }}
    {{- end }}
    {{- if eq $cloudProviderFlavor "minikube" }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "nginx-s3-gateway.selectorLabels" . | nindent 4 }}
{{- end }}