global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ''
  allowDirectoryList: false

splunkIndex: ''

authorization:
  enabled: false
  domain: dem
  url:

opentelemetry:
  # -- OpenTelemetry service name associated with this NGINX application
  serviceName: nginx
  # -- OpenTelemetry Collector endpoint address (empty disables the exporter)
  exporterHost: "localhost"
  # -- gRPC port for the OpenTelemetry Collector
  exporterPort: 4317
  # -- OpenTelemetry sampling method: AlwaysOn, AlwaysOff, TraceIdRatioBased
  samplerMethod: "AlwaysOff"
  # -- OpenTelemetry sampling ratio (percent, used when samplerMethod is TraceIdRatioBased)
  ratio: 10

image:
  repository: nginx-s3-gateway

enabled: true
environment: dev
initialDelaySeconds: 10
nodePort: 30030
replicaCount: 1
cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  imagePullSecretName: acr-registry
  flavor: openshift

env:
  protocol: TCP
  port: 80
  targetPort: 8080
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: true
  value:
    limits:
      cpu: 500m
      memory: 900Mi
    requests:
      cpu: 125m
      memory: 900Mi

ingress:
  enabled: false
  type: nginx-kubernetes # supported values: 'nginx-org' | 'nginx-kubernetes'
  host:
  path: /

route:
  enabled: true
  host:
  path: /
  tls:
    enabled: true
    useCert: true

s3:
  bucketName: dem-int
  accessKeyId: common
  secretAccessKey: commonPassword
  server: 10.8.0.9
  serverPort: 9000
  serverProto: http
  region: us-east-1
  style: path
  debug: true
  corsEnabled: true
  nginxWorkerProcesses: 4
  cacheMaxSize: 10g
  cacheInactive: 60m
  cacheValidOk: 1h
  cacheValidNotfound: 1m
  cacheValidForbidden: 30s
  # customServerConf:
  # customLocationConf:
  # sigsVersion: 4
  # allowDirectoryList: false

aws:
  sigsVersion: 4
