enabled: true
image: acrarolibotnonprod.azurecr.io/nginx-s3-gateway
imageTag: v1.2.0
replicaCount: 1
imagePullPolicy: Always

ingress:
  enabled: false

  path: "/nginx-s3-gateway/"
  host: "minikube.local"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

global:
  allowDirectoryList: "false"

deployment:
  pod:
    annotations:
      co.elastic.logs/enabled: 'true'
      co.elastic.logs/module: 'nginx'
      co.elastic.logs/fileset.stdout: 'access'
      co.elastic.logs/fileset.stderr: 'error'
      co.elastic.metrics/module: 'nginx'
      co.elastic.metrics/metricsets: 'stubstatus'
      co.elastic.metrics/hosts: '${data.host}:8080/nginx_status'
      co.elastic.metrics/period: '10s'

s3:
  bucketName: "3dtiles"
  accessKeyId: "vector"
  secretKey: "vectorPassword"
  server: "10.8.0.9"
  serverPort: "9000"
  serverProto: "http"
  region: "us-east-1"
  style: "path"
  debug: "true"
  # sigsVersion: "4"
  # allowDirectoryList: "false"

aws:
  sigsVersion: "4"

route:
  enabled: true

  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"

authentication:
  jwtPublicKeySecret: map-colonies-jwks-private
  opa:
    enabled: true
    customHeaderName: 'x-api-key'

ports:
  deployment: 8080
  nginx:
    port: 8080
    targetPort: 8080

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  port: 9191

envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  port: 8081
  maxRequestBytes: 8192
  requestedDomain: '3d'

annotations:
  collectord.io/index: SPLUNK_INDEX
  collectord.io/logs-output: splunk
  collectord.io/procstats-output: devnull
  collectord.io/netstats-output: devnull
  collectord.io/nettable-output: devnull
  collectord.io/stats-output: devnull