global:
  cloudProvider:
    dockerRegistryUrl: acrarolibotnonprod.azurecr.io
    flavor: openshift
    imagePullSecretName: "mapcolonies-secret"
  imagePullPolicy: Always
  tracing:
    enabled: true
    url: "http://infra-monitoring-opentelemetry-collector.infra-services:4318/v1/traces"
  metrics:
    enabled: true
    url: "http://localhost:55681/v1/metrics"
  environment: "development"

  S3:
    accessKey: vector
    secretAccessKey: vectorPassword
    endpoint: "http://10.8.0.9:9000"
    server: 10.8.0.9
    serverPort: 9000
    serverProto: http
    bucket: 3dtiles
    region: "us-east-1"
    style: path
    sslEnabled: false
    maxAttempts: 3
    sigVersion: 4
    storageClass: "STANDARD"

  opala:
    enabled: "true"
    domain: "3d"
    url: "http://opa-dev-opa-service.infra-services/v1/data/http/authz/decision"

cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  flavor: openshift
  imagePullSecretName: "mapcolonies-secret"
imagePullPolicy: Always
environment: "development"

image:
  repository: common/nginx-s3-gateway
  tag: test6

nodePort: 30030
replicaCount: 1
revisionHistoryLimit: 5 # Amount of revisions we keep

S3:
  accessKey: vector
  secretAccessKey: vectorPassword
  endpoint: "http://10.8.0.9:9000"
  server: 10.8.0.9
  serverPort: 9000
  serverProto: http
  bucket: 3dtiles
  region: "us-east-1"
  style: path
  sslEnabled: false
  maxAttempts: 3
  sigVersion: 4
  storageClass: "STANDARD"

opala:
  enabled: "true"
  domain: "3d"
  url: "http://opa-dev-opa-service.infra-services/v1/data/http/authz/decision"

nginx:
  maxAge:

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /health

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /health

extraVolumes: {}

extraVolumeMounts: {}

sidecars: {}

podAnnotations: {}

env:
  protocol: TCP
  port: 80
  targetPort: 8080
  debug: false
  corsEnabled: true
  nginxWorkerProcesses: 4
  allowDirectoryList: "false"
  tracing:
    enabled: true
    url: "http://infra-monitoring-opentelemetry-collector.infra-services:4318/v1/traces"
  metrics:
    enabled: true
    url: "http://localhost:55681/v1/metrics"

opentelemetry:
  # -- OpenTelemetry service name to be associated your NGINX application
  serviceName: nginx
  # -- OpenTelemetry Collector endpoint address
  exporterHost: "localhost"
  exporterPort: 4317 # gRPC port for OpenTelemetry Collector
  # -- OpenTelemetry sampling method
  samplerMethod: "AlwaysOff" # AlwaysOn, AlwaysOff, TraceIdRatioBased
  # -- OpenTelemetry sampling ratio
  ratio: 10 # between 0 and 1

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: false
  path: /
  host: localhost
  cors:
    enabled: true
    origin: "*"

route:
  enabled: true
  path: /
  host:
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
  rewriteTarget: "/"
  tls:
    enabled: false
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: false
    certificate: ""
    key: ""
    caCertificate: ""

customServerConf: "" # Example: "expires 4w;\n"
customLocationConf: "proxy_no_cache 1;\n" # Example: "proxy_no_cache 1;\n"

cache:
  maxSize: 10g
  inactive: 60m
  validOk: 1h
  validNotFound: 1m
  validForbidden: 30s
  sliceSize: 1m

redis:
  enabled: true
  host: serving-redis-master.3d-dev.svc.cluster.local
  port: 6379
  sslEnabled: false
  skipCache: 0 # 0 for false. If it contains any other value, the service will skip cache in redis
  cacheExpirationTime: 1000
  connectionTimeout: 100
  sendTimeout: 100
  readTimeout: 100
  maxIdleTimeout: 200
  poolSize: 100
  authentication:
    requirePassword: true
    password: myredis123
    username:
  prefix:
    enabled: false
    value: "bla:"
