enabled: true
image: artifactory.rnd-hub.com:6543/nginx-s3-gateway
imageTag: v1.1.0
replicaCount: 1
imagePullPolicy: Always
imagePullSecretName: mapcolonies-secret

ingress:
  enabled: true

  path: /
  host: "lb-mapcolonies.gg.wwest.local"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

global:
  allowDirectoryList: "false"

deployment:
  pod:
    annotations:
      co.elastic.logs/enabled: 'true'
      co.elastic.logs/module: 'nginx'
      co.elastic.logs/fileset.stdout: 'access'
      co.elastic.logs/fileset.stderr: 'error'
      co.elastic.metrics/module: 'nginx'
      co.elastic.metrics/metricsets: 'stubstatus'
      co.elastic.metrics/hosts: '${data.host}:8080/nginx_status'
      co.elastic.metrics/period: '10s'

s3:
  bucketName: "mapcolonies"
  accessKeyId: "nAee0Wyy0m9hvvTkttTe6OOEQtbw7-a8"
  secretKey: "yPGlawFizJUS3VcN9hpYujaeN64qLf4T"
  server: "objects.gg.wwest.local"
  serverPort: "80"
  serverProto: "http"
  region: "us-east-1"
  style: "path"
  debug: "true"
  # sigsVersion: "4"
  # allowDirectoryList: "false"

aws:
  sigsVersion: "4"

route:
  enabled: false

  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"

authentication:
  opa:
    enabled: false
    customHeaderName: 'x-api-key'
    domain: 'raster'

ports:
  deployment: 8080
  nginx:
    port: 80
    targetPort: 8080
  opa:
    port: 9191
  envoy:
    port: 8081

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3

envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  maxRequestBytes: 8192
  
