enabled: true
image: acrarolibotnonprod.azurecr.io/nginx-s3-gateway
imageTag: v1.1.1
replicaCount: 1
imagePullPolicy: Always
imagePullSecretName: mapcolonies-secret

ingress:
  enabled: false
  type: 'nginx-kubernetes' # supported values: 'nginx-org' | 'nginx-kubernetes'
  host: "*"
  path: /

route:
  enabled: true
  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"

global:
  allowDirectoryList: "false"

deployment:
  pod:
    annotations:
      co.elastic.logs/enabled: 'true'
      co.elastic.logs/module: 'nginx'
      co.elastic.logs/fileset.stdout: 'access'
      co.elastic.logs/fileset.stderr: 'error'
      co.elastic.metrics/module: 'nginx'
      co.elastic.metrics/metricsets: 'stubstatus'
      co.elastic.metrics/hosts: '${data.host}:8080/nginx_status'
      co.elastic.metrics/period: '10s'

s3:
  bucketName: "dem-int"
  accessKeyId: "raster"
  secretKey: "rasterPassword"
  server: "10.8.0.9"
  serverPort: "9000"
  serverProto: "http"
  region: "us-east-1"
  style: "path"
  debug: "true"
  # sigsVersion: "4"
  # allowDirectoryList: "false"

aws:
  sigsVersion: "4"

authentication:
  opa:
    enabled: true
    customHeaderName: 'x-api-key'
    domains: '3d'

ports:
  deployment: 8080
  nginx:
    port: 80
    targetPort: 8080
  opa:
    port: 9191
  envoy:
    port: 8081

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3

envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  maxRequestBytes: 8192
  
