gzip {{ if .Values.gzip.enabled }}on{{ else }}off{{ end }};

gzip_comp_level {{ .Values.gzip.compLevel }};

gzip_min_length {{ .Values.gzip.minLength }};

gzip_proxied {{ .Values.gzip.proxied }};

gzip_vary {{ .Values.gzip.vary }};

gzip_types
{{- range .Values.gzip.types }}
  {{ . }}
{{- end }};
