map $msec $nanosec {
    ~(.*)\.(.*) $1$2000000;
}

log_format main escape=json
'{'
    '"Timestamp":$nanosec,'
    '"Attributes":{'
        '"mapcolonies.time_local":"$time_local",'
        {{ if .Values.authorization.opa.enabled }}
        '"mapcolonies.http.auth.token.client_name":"$jwt_payload_sub",'
        {{ end }}
        '"http.request.method":"$request_method",'
        '"http.request.header.host":"$host",'
        '"http.request.header.referer":"$http_referer",'
        '"http.request.header.content-type":"$content_type",'
        '"http.request.body.size":"$content_length",'
        '"http.request.size": $request_length,'
        '"http.response.body.size": $body_bytes_sent,'
        '"http.response.header.x_forwarded_for":"$proxy_add_x_forwarded_for",'
        '"http.response.status_code":"$status",'
        '"user_agent.original":"$http_user_agent",'
        '"network.protocol.name":"$otel_network_protocol_name",'
        '"network.protocol.version":"$otel_network_protocol_version",'
        '"mapcolonies.request_time":"$request_time",'
        '"mapcolonies.http.upstream_addr":"$upstream_addr",'
        '"mapcolonies.http.upstream_status_code":"$upstream_status",'
        '"mapcolonies.http.upstream_connect_time":"$upstream_connect_time",'
        '"mapcolonies.http.upstream_response_time":"$upstream_response_time",'
        '"mapcolonies.http.upstream_response_length":"$upstream_response_length",'
        '"mapcolonies.http.upstream_bytes_sent": $upstream_bytes_sent,'
        '"mapcolonies.http.upstream_bytes_received": $upstream_bytes_received,'
        '"mapcolonies.http.upstream_cache_status":"$upstream_cache_status",'
        '"server.address":"$host",'
        '"server.port":"$server_port",'
        '"client.address":"$remote_addr",'
        '"client.port":"$remote_port",'
        '"url.scheme":"$scheme",'
        '"url.path":"$uri",'
        '"url.full":"$request_uri",'
        '"url.query":"$query_string"'
    '},'
    '"Resource":{'
        # Additional important log details should be added here
        '"host.name":"$hostname",'
        '"service.name":"{{ .Values.image.repository }}",'
        '"service.version":"{{ include "nginx-s3-gateway.tag" . }}"'
    '},'
    '"TraceId":"$otel_trace_id",' ## this is a byte sequence (hex-encoded in JSON)
    '"SpanId":"$otel_span_id",'
    '"SeverityText":"INFO",'
    '"SeverityNumber": 9,'
    '"InstrumentationScope":"access.log",'
    '"Body":"$request"'
'}';
